### ISSUE TITLE
Please add support for golines

### ISSUE THREAD

**Issue by ayoisaiah** [TekWizely/pre-commit-golang#11]
[golines](https://github.com/segmentio/golines) is a formatter for fixing long lines in a file.

**Comment by TekWizely** [comment]
Greetings!

So in preparing for my next release, I took a look at adding support for golines.

I ran into some concerns / issues

concern: Most tools like this (goreturns, goimports, gofumpt) act as drop-in replacements for gofmt, with one of the key features being support of the core gofmt cli arguments.

golines seems to have strayed off the path, namely by re-purposing `-d` to mean debug instead of show diff, with show-diff being activated via `--dry-run`

issue: The diff logic is accomplished via `"embedded Python script"`, which just feels like the wrong way to go, and in fact caused a pyenv error in my local.

So I don't feel comfortable adding a builtin hook for golines at this time.

However, you can use my newly-introduced `my-cmd` and `my-cmd-repo` hooks to invoke golines on a per-modified-file or per-repo basis, respectively.  quick examples:

```
# ...
      hooks:
            # Run 'golines -l --dry-run $FILE' for each staged .go file
        -   id: my-cmd
            name: go-lines
            alias: go-lines
            args: [ golines, -l, --dry-run ]

            # Run 'golines -l --dry-run .' in the repo root folder
        -   id: my-cmd-repo
            name: go-lines-repo
            alias: go-lines-preo
            args: [ golines, -l, --dry-run, . ]
```

Thank you for your interest in my project - I hope you will give these a try and lemme know how they work out!

-TW
