### ISSUE TITLE
Unknown flag --config with golangci-lint

### ISSUE THREAD

**Issue by Dysta** [TekWizely/pre-commit-golang#35]
Hello, after reading the doc, I faced an issue that I don't really understand.

Here is my precommit config :
```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    # ? add a hook in the order you want to run it
    hooks:
    -   id: go-fmt
        name: go fmt
    -   id: golangci-lint
        name: go lint
        args: [--config .golangci.yaml]

    -   id: go-test-pkg
        name: go test
        args: ["--hook:env:GO111MODULE=on"]
        stages: [push]
```

But the run result in a weird error:
```ERRO Can't get config for command line: can't parse args: unknown flag: --config .golangci.yaml```

Since the doc itself recommande to use the --config args, idk what i'm doing wrong to have this error.

I tested with 
```yaml
        args: ["--", --config .golangci.yaml]
```
since i read that the first "--" is consumed but I'm really blocked rn.

Thank you for help
