### ISSUE TITLE
Unable to pass `-config .revive.toml` to revive hook.

### ISSUE THREAD

**Issue by deranjer** [TekWizely/pre-commit-golang#36]
I've tried multiple ways to pass a config file to revive, but it errors out every time:

```
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
      - id: go-revive
        args: [-config, .revive.toml]
```
```
cannot parse the config file: toml: line 1: expected '.' or '=', but got 'c' instead
cannot parse the config file: toml: line 1: expected '.' or '=', but got '/' instead
cannot parse the config file: toml: line 1: expected '.' or '=', but got 'c' instead
cannot parse the config file: toml: line 1: expected '.' or '=', but got 'm' instead
```

Running it manually with `revive -config .revive.toml` works completely fine.

```
      - id: go-revive
        args: ["--", -config, .revive.toml]
```

`flag needs an argument: -config`

```
      - id: go-revive
        args: ["--", "-config", ".revive.toml"]
```
`flag needs an argument: -config`

```
      - id: go-revive
        args: ["-config .revive.toml"]
```

`flag provided but not defined: -config .revive.toml`
